const SITE_URL=(import.meta.env.VITE_SITE_URL||'https://parca-avcisi.vercel.app').replace(/\/$/,'');
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const text=el=>clean(el?.textContent);
const parsePrice=v=>{const n=String(v??'').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.');const x=Number(n);return Number.isFinite(x)&&x>0?x:null;};
const add=(id,data)=>{let s=document.head.querySelector(`script[data-pa-schema="${id}"]`);if(!s){s=document.createElement('script');s.type='application/ld+json';s.dataset.paSchema=id;document.head.appendChild(s)}s.textContent=JSON.stringify(data)};
function breadcrumb(){const path=window.location.pathname.replace(/\/+$/,'')||'/';const parts=path.split('/').filter(Boolean);const items=[{'@type':'ListItem',position:1,name:'Ana Sayfa',item:`${SITE_URL}/`}];if(parts[0]==='parcalar'&&parts[1])items.push({'@type':'ListItem',position:2,name:clean(parts[1]).replace(/-/g,' '),item:`${SITE_URL}/parcalar/${parts[1]}`});if(parts[0]==='arac'&&parts[1]&&parts[2]){items.push({'@type':'ListItem',position:2,name:'Araçlar',item:`${SITE_URL}/ilanlar`});items.push({'@type':'ListItem',position:3,name:`${parts[1].replace(/-/g,' ')} ${parts[2].replace(/-/g,' ')}`,item:`${SITE_URL}${path}`});}add('breadcrumb',{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items});}
function listingSchema(){const cards=[...document.querySelectorAll('#listingGrid .listing-card')].slice(0,24);if(!cards.length)return;const elements=cards.map((card,index)=>{const name=text(card.querySelector('h3'))||'Oto parçası';const price=parsePrice(text(card.querySelector('.price')));const image=card.querySelector('img.listing-photo')?.src;const condition=text(card.querySelector('.condition'));const item={'@type':'Product',name};if(image)item.image=[image];if(condition)item.itemCondition=condition==='Sıfır'?'https://schema.org/NewCondition':'https://schema.org/UsedCondition';if(price)item.offers={'@type':'Offer',price,currency:'TRY',availability:'https://schema.org/InStock',url:`${SITE_URL}/ilanlar`};return {'@type':'ListItem',position:index+1,item};});add('product-item-list',{'@context':'https://schema.org','@type':'ItemList',name:'Parça Avcısı Oto Parça İlanları',numberOfItems:elements.length,itemListElement:elements});}
function categorySchema(){const h1=text(document.querySelector('h1'));if(!h1)return;const path=window.location.pathname;if(!path.startsWith('/parcalar/'))return;add('category-collection',{'@context':'https://schema.org','@type':'CollectionPage',name:h1,url:`${SITE_URL}${path}`,isPartOf:{'@type':'WebSite',name:'Parça Avcısı',url:SITE_URL}});}
function run(){breadcrumb();categorySchema();listingSchema();}
run();if(document.readyState!=='complete')window.addEventListener('load',run,{once:true});const observer=new MutationObserver(()=>{if(document.querySelector('#listingGrid .listing-card'))listingSchema();});observer.observe(document.body,{childList:true,subtree:true});
export const schemaSeoReady=true;
