import { vehicleCatalog } from './vehicle-catalog.js';

const SITE_URL = (import.meta.env.VITE_SITE_URL || 'https://parca-avcisi.vercel.app').replace(/\/$/, '');
const GA_ID = import.meta.env.VITE_GA_ID || '';
const SEARCH_CONSOLE_VERIFICATION = import.meta.env.VITE_GOOGLE_SITE_VERIFICATION || '';
const CATEGORY_PAGES = {motor:'Motor',sanziman:'Şanzıman',kaporta:'Kaporta',aydinlatma:'Aydınlatma','fren-sistemi':'Fren Sistemi',suspansiyon:'Süspansiyon',elektrik:'Elektrik','ic-aksam':'İç Aksam',egzoz:'Egzoz',klima:'Klima',filtreler:'Filtreler','yakit-sistemi':'Yakıt Sistemi',direksiyon:'Direksiyon','jant-lastik':'Jant & Lastik','cam-ayna':'Cam & Ayna','sogutma-sistemi':'Soğutma Sistemi',aktarma:'Aktarma',diger:'Diğer'};
const accountPaths = new Set(['/profilim','/ilanlarim','/taleplerim','/mesajlarim','/favorilerim','/kayitli-aramalarim','/bildirimler','/musterilerim','/hesap-bilgileri','/ayarlar','/yardim-destek','/araclarim']);
const path = window.location.pathname.replace(/\/+$/, '') || '/';
const params = new URLSearchParams(window.location.search);
const category=params.get('category'),subcategory=params.get('subcategory'),vehicleType=params.get('vehicleType');
const categorySlug=path.startsWith('/parcalar/')?path.slice('/parcalar/'.length):'';
const landingCategory=CATEGORY_PAGES[categorySlug]||'';
const slug=(value)=>String(value??'').trim().toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
function setMeta(name,content){let e=document.head.querySelector(`meta[name="${name}"]`);if(!e){e=document.createElement('meta');e.name=name;document.head.appendChild(e);}e.content=content;}
function setProperty(property,content){let e=document.head.querySelector(`meta[property="${property}"]`);if(!e){e=document.createElement('meta');e.setAttribute('property',property);document.head.appendChild(e);}e.content=content;}
function setCanonical(url){let e=document.head.querySelector('link[rel="canonical"]');if(!e){e=document.createElement('link');e.rel='canonical';document.head.appendChild(e);}e.href=url;}
function addJsonLd(id,data){let e=document.head.querySelector(`script[data-seo-jsonld="${id}"]`);if(!e){e=document.createElement('script');e.type='application/ld+json';e.dataset.seoJsonld=id;document.head.appendChild(e);}e.textContent=JSON.stringify(data);}
function findVehiclePage(){const p=path.split('/').filter(Boolean);if(p[0]!=='arac'||p.length<2||p.length>3)return null;return vehicleCatalog.find(r=>slug(r?.make??r?.brand)===p[1]&&slug(r?.model)===p[2])||null;}
const vehicleRoute=path.split('/').filter(Boolean)[0]==='arac';
const vehiclePage=findVehiclePage();
const vehicleUrl=vehiclePage?`${SITE_URL}/arac/${slug(vehiclePage.make??vehiclePage.brand)}/${slug(vehiclePage.model)}`:'';
function addLandingPage(){if(!landingCategory)return;const main=document.querySelector('main');if(!main||document.querySelector('#seo-landing'))return;const s=document.createElement('section');s.id='seo-landing';s.className='section';s.innerHTML=`<div class="container"><span class="eyebrow">PARÇA AVCISI KATEGORİ</span><h1>${landingCategory} Oto Parçaları</h1><p>Aracınıza uygun ${landingCategory.toLocaleLowerCase('tr-TR')} parçalarını Parça Avcısı'nda keşfedin. Sıfır, 2. el ve çıkma seçeneklerini karşılaştırın; uygun parçayı ve satıcıyı bulun.</p><div style="display:flex;gap:12px;flex-wrap:wrap;margin-top:18px"><a class="dark-btn" href="/ilanlar?category=${encodeURIComponent(landingCategory)}">${landingCategory} ilanlarını gör</a><a class="text-btn" href="/ilanlar">Tüm ilanlara git →</a></div></div>`;main.prepend(s);}
function addVehiclePage(){if(!vehiclePage)return;const main=document.querySelector('main');if(!main||document.querySelector('#seo-vehicle-landing'))return;const make=vehiclePage.make??vehiclePage.brand,model=vehiclePage.model;const years=Array.isArray(vehiclePage.years)?vehiclePage.years.filter(Boolean):[];const engines=Array.isArray(vehiclePage.engines)?vehiclePage.engines.filter(Boolean):[];const details=[years.length?`Model yılları: ${Math.min(...years)}–${Math.max(...years)}`:'',engines.length?`Motor seçenekleri: ${engines.slice(0,8).join(', ')}`:''].filter(Boolean).join(' · ');const s=document.createElement('section');s.id='seo-vehicle-landing';s.className='section';s.innerHTML=`<div class="container"><span class="eyebrow">ARAÇ PARÇA KATALOĞU</span><h1>${make} ${model} Yedek Parça</h1><p>${make} ${model} için oto yedek parça ilanlarını Parça Avcısı'nda keşfedin. Aracınıza uygun motor, kaporta, fren, elektrik ve diğer parça seçeneklerini karşılaştırın.</p>${details?`<p class="seo-vehicle-details">${details}</p>`:''}<div style="display:flex;gap:12px;flex-wrap:wrap;margin-top:18px"><a class="dark-btn" href="/ilanlar?vehicleMake=${encodeURIComponent(make)}&vehicleModel=${encodeURIComponent(model)}">${make} ${model} ilanlarını gör</a><a class="text-btn" href="/ilanlar">Tüm oto parçalarına git →</a></div></div>`;main.prepend(s);}
const isAccount=accountPaths.has(path),isListings=path==='/ilanlar',isCategoryLanding=Boolean(landingCategory),isVehiclePage=Boolean(vehiclePage);
const hasFilterQuery=Boolean(category||subcategory||vehicleType||params.get('q')||params.get('vehicleMake')||params.get('vehicleModel'));
let title='Parça Avcısı | Oto Parça Pazaryeri',description='Sıfır, 2. el ve çıkma oto parçalarını araç uyumluluğuna göre bul, karşılaştır ve ilan ver.';
if(isListings){title='Oto Parça İlanları | Parça Avcısı';description='Oto parça ilanlarını ara, filtrele ve satıcıları karşılaştır. Sıfır, 2. el ve çıkma parçaları Parça Avcısı\'nda keşfet.';}
if(isCategoryLanding){title=`${landingCategory} Oto Parçaları | Parça Avcısı`;description=`${landingCategory} oto parçalarını Parça Avcısı\'nda keşfedin. Sıfır, 2. el ve çıkma parça ilanlarını karşılaştırın ve aracınıza uygun parçayı bulun.`;}
if(isVehiclePage){const make=vehiclePage.make??vehiclePage.brand,model=vehiclePage.model;title=`${make} ${model} Yedek Parça | Parça Avcısı`;description=`${make} ${model} yedek parça ve oto parça ilanlarını Parça Avcısı\'nda keşfedin. Aracınıza uygun parçaları karşılaştırın ve satıcıları bulun.`;}
if(category&&!isCategoryLanding&&!isVehiclePage){const label=[category,subcategory,vehicleType].filter(Boolean).join(' ');title=`${label} Oto Parçaları | Parça Avcısı`;description=`${label} oto parçalarını Parça Avcısı\'nda ara, ilanları karşılaştır ve uygun parçayı bul.`;}
if(vehicleRoute&&!isVehiclePage){title='Araç Bulunamadı | Parça Avcısı';description='Aradığınız araç kataloğu kaydı bulunamadı.';}
document.title=title;setMeta('description',description);
const noindex=Boolean(isAccount||(hasFilterQuery&&!isCategoryLanding&&!isVehiclePage)||vehicleRoute&&!isVehiclePage);
setMeta('robots',noindex?'noindex,follow':'index,follow');
const canonical=isVehiclePage?vehicleUrl:`${SITE_URL}${isCategoryLanding?`/parcalar/${categorySlug}`:isListings?'/ilanlar':vehicleRoute?path:'/'}`;setProperty('og:title',title);setProperty('og:description',description);setProperty('og:url',canonical);setProperty('og:type','website');setProperty('og:site_name','Parça Avcısı');setProperty('og:image',`${SITE_URL}/app-logo.png`);setMeta('twitter:title',title);setMeta('twitter:description',description);setCanonical(canonical);
addJsonLd('organization',{'@context':'https://schema.org','@type':'Organization',name:'Parça Avcısı',url:SITE_URL,logo:`${SITE_URL}/app-logo.png`});addJsonLd('website',{'@context':'https://schema.org','@type':'WebSite',name:'Parça Avcısı',url:SITE_URL,potentialAction:{'@type':'SearchAction',target:`${SITE_URL}/ilanlar?q={search_term_string}`,'query-input':'required name=search_term_string'}});
if(isListings||isCategoryLanding||isVehiclePage){const items=[{'@type':'ListItem',position:1,name:'Ana Sayfa',item:`${SITE_URL}/`}];if(isVehiclePage)items.push({'@type':'ListItem',position:2,name:'Araçlar',item:`${SITE_URL}/ilanlar`},{'@type':'ListItem',position:3,name:`${vehiclePage.make??vehiclePage.brand} ${vehiclePage.model}`,item:vehicleUrl});else items.push({'@type':'ListItem',position:2,name:isCategoryLanding?landingCategory:'İlanlar',item:`${SITE_URL}${isCategoryLanding?`/parcalar/${categorySlug}`:'/ilanlar'}`});addJsonLd('breadcrumb',{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items});}
if(isCategoryLanding){addLandingPage();addJsonLd('category-page',{'@context':'https://schema.org','@type':'CollectionPage',name:`${landingCategory} Oto Parçaları`,description,url:`${SITE_URL}/parcalar/${categorySlug}`});}
if(isVehiclePage){addVehiclePage();addJsonLd('vehicle-page',{'@context':'https://schema.org','@type':'CollectionPage',name:title,description,url:vehicleUrl,about:{'@type':'Product',name:`${vehiclePage.make??vehiclePage.brand} ${vehiclePage.model}`}});}
function updateListingItemList(){if(!isListings)return;const cards=[...document.querySelectorAll('#listingGrid .listing-card')];if(!cards.length)return;addJsonLd('listing-item-list',{'@context':'https://schema.org','@type':'ItemList',name:'Parça Avcısı oto parça ilanları',itemListElement:cards.slice(0,24).map((card,index)=>({'@type':'ListItem',position:index+1,name:card.querySelector('h3')?.textContent?.trim()||'Oto parçası'}))});}
if(isListings){const observer=new MutationObserver(updateListingItemList);observer.observe(document.body,{childList:true,subtree:true});window.setTimeout(updateListingItemList,1500);}
if(SEARCH_CONSOLE_VERIFICATION)setMeta('google-site-verification',SEARCH_CONSOLE_VERIFICATION);if(GA_ID&&!document.querySelector(`script[data-pa-ga="${GA_ID}"]`)){const script=document.createElement('script');script.async=true;script.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(GA_ID)}`;script.dataset.paGa=GA_ID;document.head.appendChild(script);window.dataLayer=window.dataLayer||[];window.gtag=function gtag(){window.dataLayer.push(arguments);};window.gtag('js',new Date());window.gtag('config',GA_ID,{anonymize_ip:true});}
document.addEventListener('submit',(event)=>{if(event.target?.id==='searchForm'||event.target?.id==='listingPageSearchForm'){const input=event.target.querySelector('input');if(typeof window.gtag==='function')window.gtag('event','search',{search_term:input?.value?.trim()||''});}});export function trackSeoEvent(name,eventParams={}){if(typeof window.gtag==='function')window.gtag('event',name,eventParams);}
