import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const seedPath = path.join(root, 'data/vehicle-catalog-sources/legacy-seed.json');
const outJson = path.join(root, 'data/vehicle-catalog-merged.json');
const outJs = path.join(root, 'src/lib/vehicle-catalog.js');
const VEHICLEDB_URL = 'https://cdn.jsdelivr.net/gh/vehiclesdb/vehiclesdb@latest/dist/vehicles.json';
const INFOCAR_URL = 'https://raw.githubusercontent.com/alihaydarkir/InformationCar/master/data/arabalar.json';
const FLEET_MAKES = 'https://fleetbyte-api.onrender.com/v1/makes?page=1&pageSize=100';
const clean = (v) => String(v ?? '').replace(/\s+/g, ' ').trim();
const key = (...v) => v.map(clean).join('|').toLocaleLowerCase('tr-TR');

async function getJson(url) { const res = await fetch(url, { headers: { 'User-Agent': 'Parca-Avcisi-Vehicle-Merger/1.0' } }); if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${url}`); return res.json(); }
async function loadLegacy() { try { return JSON.parse(await fs.readFile(seedPath, 'utf8')); } catch {} return []; }
function add(records, seen, row, source) {
  const make = clean(row.make || row.marka), model = clean(row.model); if (!make || !model) return;
  const engines = Array.isArray(row.engines) ? row.engines.map(clean).filter(Boolean) : (row.engine ? [clean(row.engine)] : []);
  const trims = Array.isArray(row.trims) ? row.trims.map(clean).filter(Boolean) : (row.trim ? [clean(row.trim)] : []);
  const item = { type: clean(row.type) || 'Otomobil', make, model, generation: clean(row.generation) || undefined, body: clean(row.body) || undefined, years: Array.isArray(row.years) ? row.years.map(Number).filter(Boolean) : [], year_from: row.year_from ?? undefined, year_to: row.year_to ?? undefined, engines, fuels: Array.isArray(row.fuels) ? row.fuels.map(clean).filter(Boolean) : [], transmissions: Array.isArray(row.transmissions) ? row.transmissions.map(clean).filter(Boolean) : [], trims, engineDetails: row.engineDetails ?? [], provenance: [source] };
  const k = key(make, model, item.generation, item.body, item.year_from, item.year_to, engines.join(','), trims.join(',')); if (seen.has(k)) return; seen.add(k); records.push(item);
}
function importInfoCar(records, seen, data) { for (const r of Array.isArray(data) ? data : []) add(records, seen, { type:'Otomobil', make:r.marka, model:r.model, engines:r.motor ? [clean(r.motor)+' cc'] : [], fuels:r.yakit ? [clean(r.yakit)] : [], transmissions:r.vites ? [clean(r.vites)] : [], trims:r.donanim ? [clean(r.donanim)] : [] }, 'InformationCar'); }
function flattenVehiclesDb(data) { const out=[]; if (Array.isArray(data)) { for (const m of data) { if(m?.make&&m?.name) out.push(m); else if(m?.name&&Array.isArray(m.models)) for(const x of m.models) out.push({make:m.name,...x}); } } else if(data?.makes) { for(const m of data.makes) for(const x of (m.models||[])) out.push({make:m.name,...x}); } return out; }
function importVehiclesDb(records, seen, data, allowed) { for(const r of flattenVehiclesDb(data)) { const make=clean(r.make||r.make_name); if(!allowed.has(make.toLocaleLowerCase('tr-TR'))) continue; add(records,seen,{type:r.kind==='van'?'Panelvan':r.kind==='truck'?'Kamyon':r.kind==='bus'?'Otobüs':r.kind==='motorcycle'?'Motosiklet':'Otomobil',make,model:r.name,generation:r.generation?.name,body:Array.isArray(r.body_types)?r.body_types[0]:r.body_type,year_from:r.year_start??r.years?.[0],year_to:r.year_end??r.years?.at(-1),years:Array.isArray(r.years)?r.years:[]},'VehiclesDB'); } }
async function enrichFleetByte(records, seen) { if(process.env.FLEETBYTE!=='1') return {fetched:0,skipped:true}; let fetched=0; try { const makes=await getJson(FLEET_MAKES); for(const make of (makes.items||[])) { if(clean(make.country).toUpperCase()!=='TR') continue; const models=await getJson(`https://fleetbyte-api.onrender.com/v1/makes/${make.id}/models?page=1&pageSize=100`); for(const model of (models.items||[])) { const variants=await getJson(`https://fleetbyte-api.onrender.com/v1/models/${model.id}/variants?page=1&pageSize=100`); for(const v of (variants.items||[])) { add(records,seen,{make:make.name,model:model.name,years:v.year?[Number(v.year)]:[],year_from:v.year,year_to:v.year,body:v.bodyType,engines:[v.engine].filter(Boolean),fuels:[v.fuelType].filter(Boolean),transmissions:[v.gearboxType].filter(Boolean),trims:[v.name].filter(Boolean)},'FleetByte'); fetched++; } } } } catch(e) { console.warn(`FleetByte enrichment skipped: ${e.message}`); } return {fetched,skipped:false}; }

const records=[], seen=new Set(); for(const row of await loadLegacy()) add(records,seen,row,'ParcaAvcisiLegacy');
let info=[]; try { info=await getJson(INFOCAR_URL); importInfoCar(records,seen,info); } catch(e){ console.warn(`InformationCar skipped: ${e.message}`); }
try { const vdb=await getJson(VEHICLEDB_URL); importVehiclesDb(records,seen,vdb,new Set(records.map(x=>x.make.toLocaleLowerCase('tr-TR')))); } catch(e){ console.warn(`VehiclesDB skipped: ${e.message}`); }
const fleet=await enrichFleetByte(records,seen); records.sort((a,b)=>key(a.make,a.model,a.generation,a.body).localeCompare(key(b.make,b.model,b.generation,b.body),'tr'));
const payload={version:new Date().toISOString().slice(0,10),scope:'TR-first vehicle catalog',policy:'No inferred fitment; explicit source provenance is preserved.',sources:[{id:'ParcaAvcisiLegacy',status:'seed'},{id:'InformationCar',url:INFOCAR_URL,status:info.length?'loaded':'failed'},{id:'VehiclesDB',url:VEHICLEDB_URL,license:'CC-BY-4.0',status:'loaded'},{id:'FleetByte',status:fleet.skipped?'optional':'loaded',fetched:fleet.fetched}],counts:{records:records.length,makes:new Set(records.map(x=>x.make)).size,models:new Set(records.map(x=>key(x.make,x.model))).size},records};
await fs.mkdir(path.dirname(outJson),{recursive:true}); await fs.writeFile(outJson,JSON.stringify(payload,null,2)+'\n');
const js=`// GENERATED FILE — do not edit manually.\nexport const vehicleTypes=['Otomobil','SUV / 4x4','Pickup / Kamyonet','Panelvan','Minibüs','Kamyon','Otobüs','Motosiklet','Ticari Araç','Diğer'];\nexport const vehicleCatalog=${JSON.stringify(records,null,2)};\nconst clean=v=>String(v??'').trim();\nconst unique=a=>[...new Set(a.map(clean).filter(Boolean))];\nexport function getMakes(){return unique(vehicleCatalog.map(x=>x.make));}\nexport function getModels(make){return unique(vehicleCatalog.filter(x=>clean(x.make)===clean(make)).map(x=>x.model));}\nexport function getYears(make,model){const rows=vehicleCatalog.filter(x=>clean(x.make)===clean(make)&&clean(x.model)===clean(model)); const years=rows.flatMap(x=>x.years?.length?x.years:range(x.year_from,x.year_to)); return unique(years).sort((a,b)=>Number(a)-Number(b));}\nexport function getVehicleVariants(make,model,year){return vehicleCatalog.filter(x=>clean(x.make)===clean(make)&&clean(x.model)===clean(model)&&(!year||!x.years?.length||x.years.includes(Number(year)))).map(x=>({generation:x.generation??null,body:x.body??null,engine:x.engines??[],fuel:x.fuels??[],transmission:x.transmissions??[],trim:x.trims??[]}));}\nexport function optionsFor(selection,field){if(field==='type')return unique(vehicleCatalog.filter(x=>!selection.type||x.type===selection.type).map(x=>x.type)).sort((a,b)=>a.localeCompare(b,'tr'));if(field==='make')return unique(vehicleCatalog.filter(x=>!selection.type||x.type===selection.type).map(x=>x.make)).sort((a,b)=>a.localeCompare(b,'tr'));if(field==='model')return getModels(selection.make);if(field==='year')return getYears(selection.make,selection.model).map(String);if(field==='engine'){return unique(getVehicleVariants(selection.make,selection.model,selection.year).flatMap(x=>[...x.engine,...x.trim])).sort((a,b)=>a.localeCompare(b,'tr'));}return [];}\nfunction range(a,b){const out=[];if(!Number.isFinite(Number(a)))return out;for(let y=Number(a);y<=Number(b||a);y++)out.push(y);return out;}\n`;
await fs.writeFile(outJs,js); console.log(JSON.stringify(payload.counts));
